services:
  - type: web
    name: localscaling-backend
    env: node
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: node -r tsconfig-paths/register dist/server.js
    plan: free
